services:
  - docker
before_install:
    - docker pull teners/compiler-workout-ci
script:
    - docker run --name compiler-workout-ci -e "$TRAVIS_COMMIT=$($TRAVIS_COMMIT)" compiler-workout-ci sh test.sh
