language: c
services:
  - docker
before_install:
    - docker pull teners/compiler-workout-ci
    - docker run -d -it --name compiler-workout-ci -e "TRAVIS_COMMIT=$TRAVIS_PULL_REQUEST_BRANCH" teners/compiler-workout-ci
script:
     docker exec -it compiler-workout-ci sh test.sh
